name: Sync Fork

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/flourishbhp/flourish-reports.git"
        source_branch: "develop"
        destination_repo: "https://github.com/${{ github.repository }}.git"
        destination_branch: "develop"
        github_token: ${{ secrets.GITHUB_TOKEN }}